# Pentagonal numbers are generated by the formula, 
# Pn=n(3n−1)/2. The first ten pentagonal numbers are:
#   
# 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
# 
# It can be seen that P4 + P7 = 22 + 70 = 92 = P8.
# However, their difference, 70 − 22 = 48, is not pentagonal.
# 
# Find the pair of pentagonal numbers, 
# Pj and Pk, for which their sum and difference 
# are pentagonal and D = |Pk − Pj| is minimised;
# what is the value of D?

# Libraries
library(dplyr)

# Create the first 10,000 pentagonal numbers 
pentagonal = function(n){ n * (3 * n - 1) / 2 }
toppentagonal = pentagonal(1:10000)

# Combine the pentagonal numbers to obtain 10^8 combinations
# Then filter out the ones that have Sum and Diff in pentagonal
expand.grid(toppentagonal, toppentagonal) %>% 
  filter(Var1 > Var2) %>% 
  mutate(PSum = Var1 + Var2,
         PDiff = Var1 - Var2) %>% 
  filter(PSum %in% toppentagonal,
         PDiff %in% toppentagonal)

